steps:
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['cp', '${_ENV_PATH}', '.env']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'asia-southeast2-docker.pkg.dev/${_PROJECT_ID}/jogjaku-api/jogjaku-api', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-southeast2-docker.pkg.dev/${_PROJECT_ID}/jogjaku-api/jogjaku-api']
  - name: "gcr.io/cloud-builders/gcloud"
    args: ['run', 'deploy', 'jogjaku-api', '--image', 'asia-southeast2-docker.pkg.dev/${_PROJECT_ID}/jogjaku-api/jogjaku-api', '--region', 'asia-southeast2', '--platform', 'managed', '--allow-unauthenticated']

options:
  logging: CLOUD_LOGGING_ONLY
