steps:
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['cp', '${_ENV_PATH}', '.env']
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/${_PROJECT_ID}/{_PROJECT_NAME}', '.' ]
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'gcr.io/${_PROJECT_ID}/{_PROJECT_NAME}']
  - name: "gcr.io/cloud-builders/gcloud"
    args: ['run', 'deploy', '{_PROJECT_NAME}', '--image', 'gcr.io/${_PROJECT_ID}/{_PROJECT_NAME}', '--region', 'asia-southeast2', '--platform', 'managed', '--allow-unauthenticated']